### PR TITLE
Play into subsequent track(s) if requested length requires it

### LINKED ISSUE #50: CDDA: does not continue into subsequent track(s) if playback length requires it
The CDDA code currently handles "beyond-end-of-file" reads as invalid: it will play up-to the end of the track, and not beyond it.  This behavior turns out to be incorrect, and the playback should carry into into the next track.

The GoG release of Betrayal at Krondor (which uses cue+oggs), either due to a CD mastering issues or a faulty rip, can sometimes request playback of a given track at the tail end of the prior track.  For example: if it wants to play track 16 for 44 seconds, it requests to play track 15 at its 99% position (which is merely a blip of audio), and the game expects playback to carry on into track 16 for roughly 42 second (minus the blip in track 15).

The bin+cue version of the game is not affected by this.  In testing hundreds of CD-DA games, this is the first game encountered that requests playing more audio frames than are present in the track being played.

Issue reported by Dagar and Pr3tty F1y, and confirmed as a bug by ripsaw8080. Thank you!

### PR DESCRIPTION
**Pull request by krcroft**
Fixes #50

In debugging and performing this fix, many debug messages were improved as well as making some small small code adjustments to improve readability, such as using iterators for a given track, `track->attribute` instead of subtracting into the array vector `tracks[track -1].attribute`

### CODE REVIEW

File: src/dos/cdrom_image.cpp [hunk 1]
```diff
@@ -700,14 +834,19 @@ bool CDROM_Interface_Image::LoadIsoFile(char* filename)
...
+
 	int seek = 16 * sectorSize;	// first vd is located at sector 16
 	if (sectorSize == RAW_SECTOR_SIZE && !mode2) seek += 16;
 	if (mode2) seek += 24;
 	file->read(pvd, seek, COOKED_SECTOR_SIZE);
 	// pvd[0] = descriptor type, pvd[1..5] = standard identifier, pvd[6] = iso version (+8 for High Sierra)
-	return ((pvd[0] == 1 && !strncmp((char*)(&pvd[1]), "CD001", 5) && pvd[6] == 1) ||
-			(pvd[8] == 1 && !strncmp((char*)(&pvd[9]), "CDROM", 5) && pvd[14] == 1));
+	return ((pvd[0] == 1 && !strncmp((char*)(&pvd[1]), "CD001", 5) && pvd[6]  == 1) ||
+	        (pvd[8] == 1 && !strncmp((char*)(&pvd[9]), "CDROM", 5) && pvd[14] == 1));
```
Comment (dreamer) [inline src/dos/cdrom_image.cpp]: Maybe just compare to strings `"\1CD001\1"` and `"\1CDROM\1"`?

File: src/dos/cdrom_image.cpp [hunk 2]
```diff
@@ -959,12 +1095,14 @@ bool CDROM_Interface_Image::AddTrack(Track &curr, int &shift, int prestart, int
...
-			return true;
+	bool result = false;
+	for(track_iter track = tracks.begin(); track != tracks.end(); track++) {
+		if (track->attr == 0x40) {
+			result = true;
+			break;
 		}
 	}
-	return false;
+	return result;
```
Comment (dreamer) [inline src/dos/cdrom_image.cpp]: for (const auto &track : tracks) {
        if (track.attr = 0x40)
            return true;
    }
    return false;

?

(this code asks for functional programming one-liner, alas - this is C++)

File: src/dos/cdrom_image.cpp [hunk 3]
```diff
@@ -1064,17 +1202,14 @@ bool CDROM_Interface_Image::GetCueString(string &str, istream &in)
...
-
-	TrackFile* last = nullptr;
-	while(i != end) {
-		Track &curr = *i;
-		if (curr.file != last) {
-			delete curr.file;
-			last = curr.file;
+	track_iter track = tracks.begin();
+	track_const_iter end = tracks.end();
+	while(track != end) {
```
Comment (dreamer) [inline src/dos/cdrom_image.cpp]: Like in the previous comment, using foreach loop will make this code shorter and a bit nicer :)

File: src/misc/support.cpp [hunk 4]
```diff
@@ -17,16 +17,15 @@
...
+#include <cctype>
 #include <ctype.h>
 #include <stdarg.h>
 #include <stdio.h>
-#include <string.h>
-#include <algorithm>
-#include <cctype>
+#include <stdlib.h>
 #include <string>
+#include <string.h>
```
Comment (dreamer) [inline src/misc/support.cpp]: Let's convert it to `cstring` already, as it should've been done already by upstream…

File: src/dos/cdrom_image.cpp [hunk 5]
```diff
@@ -45,19 +42,14 @@
...
-	time(&rawtime);
-	const struct tm* ptime = localtime(&rawtime);
-	snprintf(time_str, sizeof(time_str), "%02d:%02d:%02d", ptime->tm_hour, ptime->tm_min, ptime->tm_sec);
-	return time_str;
-}
-#endif
+// STL type shorteners, local to this file
+typedef vector<CDROM_Interface_Image::Track>::iterator        track_iter;
+typedef vector<CDROM_Interface_Image::Track>::const_iterator  track_const_iter;
+typedef vector<CDROM_Interface_Image::Track>::size_type       tracks_size_t;
```
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Very nice! Fixed in d52c972a

File: src/dos/cdrom_image.cpp [hunk 6]
```diff
@@ -397,134 +416,201 @@ bool CDROM_Interface_Image::GetMediaTrayStatus(bool& mediaPresent, bool& mediaCh
...
-	const int track = GetTrack(start) - 1;
+	bool rcode = false;
+	track_const_iter track(GetTrack(start));
 
-	// The CDROM Red Book standard allows up to 99 tracks, which includes the data track
-	if ( track < 0 || track > 99 )
-		LOG(LOG_MISC, LOG_WARN)("Game tried to load track #%d, which is invalid", track);
+	// Guard 1: Does the requested start fall within out tracks
+	if (track == tracks.end())
+		LOG_MSG("CDROM: Requested sector %lu is outside our %d tracks",
```
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Keeps getting better.  Fixed in 164e4d8b

File: src/dos/cdrom_image.cpp [hunk 7]
```diff
@@ -397,134 +416,201 @@ bool CDROM_Interface_Image::GetMediaTrayStatus(bool& mediaPresent, bool& mediaCh
...
+	else if (player.channel == nullptr)
+		LOG_MSG("CDROM: The CD player's mixer channel hasn't been allocated yet");
+
+	// Finished without hitting any of the above issues? Great!
+	else rcode = true;
+
+	// Guard 7: Check if we failed any of the above..
+	if (rcode == false) {
+		StopAudio();
+		// SDL_UnlockMutex(player.mutex);
```
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Good catch - yes, cleaned up.

File: src/dos/cdrom_image.cpp [hunk 8]
```diff
@@ -397,134 +416,201 @@ bool CDROM_Interface_Image::GetMediaTrayStatus(bool& mediaPresent, bool& mediaCh
...
+	//       file itself - such as in the pre-gap region. Therefore, we clamp the offset within the
+	//       bounds of the actual track.
+
+	const int relative_start = start - track->start;
+	// If the request falls in the pregap we deduct the difference from the playback duration.
+	if (relative_start < 0) {
+		len -= relative_start;
+	}
+	// Seek to the calculated byte offset
+	const int offset(track->skip + clamp(relative_start, 0, track->length - 1) * track->sectorSize);
```
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: I agree; not benefit as it's not an object. Fixed in 53d0a489

File: src/dos/cdrom_image.cpp [hunk 9]
```diff
@@ -397,134 +416,201 @@ bool CDROM_Interface_Image::GetMediaTrayStatus(bool& mediaPresent, bool& mediaCh
...
+	// Convert the requested absolute start sector to a byte offset relative to the track's start
+	// Note: even though 'GetTrack() has determined the requested sector falls within our given
+	//       track, it's still possible that the sector is outside of the "physical" bounds of the
+	//       file itself - such as in the pre-gap region. Therefore, we clamp the offset within the
+	//       bounds of the actual track.
+
+	const int relative_start = start - track->start;
+	// If the request falls in the pregap we deduct the difference from the playback duration.
+	if (relative_start < 0) {
+		len -= relative_start;
```
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: The pregap on physical CD's will count toward the number of played frames, however file-based tracks only have a logical pregap fabricated by dosbox, so our start position is actually "moved ahead" to the start of  the audio-file; so in these cases we deduct any pregap frames from the requested duration to avoid playing further into the file or into the next file. 
(poorly worded.. need a little picture to do it justice :-)

File: src/dos/cdrom_image.cpp [hunk 10]
```diff
@@ -557,78 +652,117 @@ bool CDROM_Interface_Image::LoadUnloadMedia(bool unload)
...
+			        sector,
+			        track->number,
+			        track->start,
+			        track->start + track->length);
 		}
-		i++;
+	} else if (track == tracks.end()) {
+		LOG_MSG("CDROM: GetTrack at sector %d => fell outside the bounds of our %d tracks",
+		        sector,
+				static_cast<int>(tracks.size()));
```
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Indeed! Fixes in cfd71f81

File: src/dos/cdrom_image.cpp [hunk 11]
```diff
@@ -557,78 +652,117 @@ bool CDROM_Interface_Image::LoadUnloadMedia(bool unload)
...
-		if (decoded_track_frames == 0
-		    || player.playedTrackFrames + desired_track_frames >= player.totalTrackFrames) {
-			player.cd->StopAudio();
-		}
+	// Guard 1: Bail if we're asked to decode no frames
+	if (desired_track_frames == 0
+	// Guard 2: Bail if our player's trackFile hasn't been assigned
+	|| player.trackFile == nullptr
+	// Guard 3: Bail if our player's CD object hasn't been assigned
+	|| player.cd == nullptr) {
```
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Unwrapped; fixed in 97411952

File: src/dos/cdrom_image.cpp (hunk 1 above)
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Legacy code that I was just aligning to read cleaner; reluctant to touch its actual content.

File: src/dos/cdrom_image.cpp (hunk 2 above)
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Yes, that's more obvious - fixed in 91930311

File: src/misc/support.cpp (hunk 4 above)
Comment (krcroft) [reply src/misc/support.cpp]: Yes, fixed in fb18d4e0

File: src/dos/cdrom_image.cpp (hunk 3 above)
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: very nice! I haven't used this syntax, so need to get comfortable with it.
The "auto" everything approach feels like the wheels have flown off; but I just have to trust the compiler to work out the object's iterator types.
Fixed in 7d257ac5

File: src/dos/cdrom_image.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: The GCC build on Windows choked on `%zu`; new change in 7c4885c4 tries to use `#define __USE_MINGW_ANSI_STDIO 1` to let MinGW use it's own functions that comply with C11.
I've added that to `configure.ac` so all our code can benefit from `%zu` (when building with GCC under Windows).

[the remark this answers is not in the document]
Comment (dreamer) [reply src/dos/cdrom_image.cpp]: I didn't expect GCC to have a problem with it… I googled a bit and some people recommend using `_POSIX_C_SOURCE` instead of `__USE_MINGW_ANSI_STDIO` - I have no strong preference, but MINGW macro, being internal to the compiler, seems a bit scary.

GCC 9.2 on Fedora 30 defaults to `200809L`, which corresponds to IEEE Standard 1003.1-2008 (I have no idea which POSIX version added `%zu`).

File: src/dos/cdrom.h [hunk 12]
```diff
@@ -117,7 +121,8 @@ class CDROM_Interface_SDL : public CDROM_Interface
 	virtual bool	PlayAudioSector		(unsigned long start,unsigned long len);
 	virtual bool	PauseAudio			(bool resume);
 	virtual bool	StopAudio			(void);
-	virtual void	ChannelControl		(TCtrl ctrl) { return; };
+	virtual void	ChannelControl		(TCtrl ctrl) { (void)ctrl; // unused but part of the API
+	                                                   return; };
```
Comment (krcroft) [inline src/dos/cdrom.h]: broken formatting

File: src/dos/cdrom.h [hunk 13]
```diff
@@ -143,17 +148,19 @@ class CDROM_Interface_Fake : public CDROM_Interface
 	bool	PlayAudioSector		(unsigned long /*start*/,unsigned long /*len*/) { return true; };
 	bool	PauseAudio			(bool /*resume*/) { return true; };
 	bool	StopAudio			(void) { return true; };
-	void	ChannelControl		(TCtrl ctrl) { return; };
+	void	ChannelControl		(TCtrl ctrl) { (void)ctrl; // unused by part of the API
+	                                           return; };
```
Comment (krcroft) [inline src/dos/cdrom.h]: formatting

File: include/support.h [hunk 14]
```diff
@@ -38,6 +39,14 @@
 #include <strings.h>
 #endif
 
+// Clamp: given a value that can be compared with the given minimum and maximum
+//        values, this function will:
+//          * return the value if it's in-between or equal to either bounds, or
+//          * return either bound depending on which bound the value is beyond
+template <class T> T clamp(const T& n, const T& lower, const T& upper) {
+	return (std::max)(lower, (std::min)(n, upper));
```
Comment (krcroft) [inline include/support.h]: wrapping the functions with parentheses allows msvc to build cleanly. add as comment.

File: src/dos/cdrom.h [hunk 15]
```diff
@@ -117,7 +121,8 @@ class CDROM_Interface_SDL : public CDROM_Interface
 	virtual bool	PlayAudioSector		(unsigned long start,unsigned long len);
```
Comment (krcroft) [inline src/dos/cdrom.h]: clean up the formatting for this class now that we've touched it

File: src/dos/cdrom_image.cpp [hunk 16]
```diff
@@ -36,62 +33,65 @@
...
+#include <cstring>
 #endif
 
 #include "drives.h"
 #include "support.h"
 #include "setup.h"
 
+// Allow MinGW to use its C11 functions instead of mscvrt
+#if defined(__GNUC__) && defined(__MINGW32__)
+#define __USE_MINGW_ANSI_STDIO 1
```
Comment (krcroft) [inline src/dos/cdrom_image.cpp]: this seems to be worthless.. strip it from configure.ac and here.  fall back to int cast to make mscvrt happy.

File: src/dos/cdrom_image.cpp [hunk 17]
```diff
@@ -36,62 +33,65 @@
...
-		file->seekg(0, ios::end);
-		length = static_cast<int>(file->tellg());
-		file->seekg(original_pos, ios::end);
-	}
+	// Guard: only proceed with a valid file
+	if (file == nullptr) return -1;
+
+	std::streampos original_pos = file->tellg();
+	file->seekg(0, ios::end);
+	const int length(static_cast<int>(file->tellg()));
```
Comment (krcroft) [inline src/dos/cdrom_image.cpp]: switch to assignment

File: src/dos/cdrom_image.cpp [hunk 18]
```diff
@@ -533,102 +621,184 @@ void CDROM_Interface_Image::ChannelControl(TCtrl ctrl)
...
+			        sector,
+			        track->number,
+			        track->start,
+			        track->start + track->length);
+		}
+	} else if (track == tracks.end()) {
+		LOG_MSG("CDROM: GetTrack at sector %d => fell outside "
+		        "the bounds of our %zu tracks",
+		        sector,
+				tracks.size());
```
Comment (krcroft) [inline src/dos/cdrom_image.cpp]: formatting

File: src/dos/cdrom_image.cpp [hunk 19]
```diff
@@ -533,102 +621,184 @@ void CDROM_Interface_Image::ChannelControl(TCtrl ctrl)
...
-
-	while(i != end) {
-		Track &curr = *i;
-		Track &next = *(i + 1);
-		if (curr.start <= sector && sector < next.start) {
-			return curr.number;
+	// Guard if we have no tracks or the sector is out of bounds
+	if (sector < 0 ||
+	    sector > MAX_REDBOOK_SECTOR ||
+		tracks.size() < 2 ||
```
Comment (krcroft) [inline src/dos/cdrom_image.cpp]: formatting

File: include/support.h (hunk 14 above)
Comment (dreamer) [reply include/support.h]: I suspect forcing template parameter with:

    std::max<T>(lower, std::min<T>(n, upper));

might work as well.

File: src/dos/cdrom.h (hunk 15 above)
Comment (dreamer) [reply src/dos/cdrom.h]: I think the long term plan is to remove this class, as it's problematic for SDL2, so I wouldn't bother ;)

File: src/dos/cdrom_image.cpp (hunk 16 above)
Comment (dreamer) [reply src/dos/cdrom_image.cpp]: OK; as I mentioned earlier, we can try `_POSIX_C_SOURCE` - but it doesn't need to happen as part of this review.

File: include/support.h (hunk 14 above)
Comment (krcroft) [reply include/support.h]: Will try it out!

File: src/dos/cdrom.h (hunk 15 above)
Comment (krcroft) [reply src/dos/cdrom.h]: Good stuff!

File: src/dos/cdrom_image.cpp (hunk 16 above)
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Trying ..

File: include/support.h (hunk 14 above)
Comment (krcroft) [reply include/support.h]: This worked; great hunch! Fixed in 03d870b

File: src/dos/cdrom_image.cpp (hunk 16 above)
Comment (krcroft) [reply src/dos/cdrom_image.cpp]: Still not liking the `%zu`; will fall back to the `static<int>` cast for now.

**Comment by krcroft** [comment]
Reverted to casting instead of using %zu and building clean; all set I think.

**Comment by krcroft** [comment]
Something unexpected! Destruction Derby now plays its CDDA, without any special MSF code either. Somehow the changes here have fixed whatever was causing it to not play.

**Comment by krcroft** [comment]
[destruction_derby-split-0.gz](https://github.com/dreamer/dosbox-staging/files/3883241/destruction_derby-split-0.gz)
[destruction_derby-split-1.gz](https://github.com/dreamer/dosbox-staging/files/3883242/destruction_derby-split-1.gz)
[destruction_derby-split-2.gz](https://github.com/dreamer/dosbox-staging/files/3883243/destruction_derby-split-2.gz)
[destruction_derby-split-3.gz](https://github.com/dreamer/dosbox-staging/files/3883244/destruction_derby-split-3.gz)
[destruction_derby-split-4.gz](https://github.com/dreamer/dosbox-staging/files/3883245/destruction_derby-split-4.gz)
[destruction_derby-split-5.gz](https://github.com/dreamer/dosbox-staging/files/3883246/destruction_derby-split-5.gz)
[destruction_derby-split-6.gz](https://github.com/dreamer/dosbox-staging/files/3883247/destruction_derby-split-6.gz)
[destruction_derby-split-7.gz](https://github.com/dreamer/dosbox-staging/files/3883248/destruction_derby-split-7.gz)
[destruction_derby-split-8.gz](https://github.com/dreamer/dosbox-staging/files/3883249/destruction_derby-split-8.gz)
[destruction_derby-split-9.gz](https://github.com/dreamer/dosbox-staging/files/3883250/destruction_derby-split-9.gz)

Test commands:
```
cat destruction_derby-split-* | tar zx
cd "Destruction Derby"
/usr/src/dosbox-staging/src/dosbox start.bat
```
That loads the 48 OPUS audio tracks. The `vorbis.bat` will load `.ogg` tracks instead.
Then try with SVN running `vorbis.bat`.

File: src/dos/cdrom_image.cpp [hunk 20]
```diff
@@ -279,116 +282,144 @@ bool CDROM_Interface_Image::GetUPC(unsigned char& attr, char* upc)
...
-		        relPos.fr);
+		LOG_MSG("CDROM: GetAudioSub => playback position lands outside of our tracks");
 #endif
+		return false;
 	}
-	return rcode;
+
+	track_num = track->number;
+	attr = track->attr;
+	index = 1;
```
Comment (dreamer) [inline src/dos/cdrom_image.cpp]: This is weird… GitHub colorized `index` as if it was a keyword or a function…

(seems not to be an issue for compiler, but it's curious)
