### PR TITLE
Assess the mouse capture state when gaining window focus

### LINKED ISSUE #242: Mouse cursor visibility issues
Another ticket to report an annoying bug with respect to the mouse cursor. 

* Description
System cursor is always apparent (by default top-left corner) whatever value is set for `capture_mouse =`. On some games (ie. Command & Conquer or Red Alert) the system cursor will blend/superpose with the game cursor hence it's not that a big problem. Yet on game like Theme Hospital for instance cursors won't blend and game cursor will act as a "ghost". It's like having 2 cursors on the screen which is annoying.

* To Reproduce
Launch Theme Hospital (HOSPITAL.EXE) or whatever game which requires a mouse. In Theme Hospital at the main menu (where a doctor points the various options) the cursor won't blend with the game. Meaning 2 cursors are apparent on the screen. I haven't compiled Dosbox with screenshot support :(
NOTE: with the current Dosbox SVN (default in Retropie) no problem with cursor. No system cursor apparent only the one from the game.
NOTE2: if a value different from `capture_mouse    = seamless middlerelease` is being set then mouse in the game won't work. System cursor will still be there and working but you can't control the game.

* Expected behaviour
No system cursor visible. Just the one from the current game.

* Environment:
Raspbian Jessie (the one shipped with Retropie+all packages up-to-date)
Retropie Version 4.5.18 (latest)
Pi3B+
SDL2 (no dispmanx)
I've compiled Dosbox-staging this morning after I saw the commits for SDL texture.

* Dosbox config (Theme Hospital)
```
fullscreen       = true
vsync            = false
fullresolution   = desktop
windowresolution = desktop
output           = texture
texture_renderer = auto
capture_mouse    = seamless middlerelease
sensitivity      = 100
waitonerror      = true
priority         = higher,normal
mapperfile       = mapper-SVN.map

language = 
machine  = svga_s3
captures = capture
memsize  = 16

frameskip = 0
aspect    = true
scaler = none

core = dynamic
cputype   = auto
cycles = max
cycleup   = 10
cycledown = 20
[...] // everything else as default
```

### PR DESCRIPTION
**Pull request by kcgen**
This fixes mouse visibility issues on the Raspberry Pi, which uses an older customized version of SDL2. SDL2 on the Pi fires different windows events in a different order, making dealing with states challenging.

To handle this generically, we additionally assess the mouse capture state after the Window has gained focus.

We also add a "has_focus" state tracking boolean to the SDL object, which protects against general SDL mouse trigger events from changing the mouse state before the Window has "risen" and delivered us an EXPOSED or FOCUS event. In the prior code rapidly clicking the mouse while DOSBox was starting could freeze the mouse cursor in place on the Pi.

We still also assess the mouse state on EXPOSE events, which is fired after full - windowed modes are toggled. The EXPOSE even occurs reliably on OSX, X11, Wayland, and Windows after the window has settled (but is never fired on the Pi).

Fixes #242.

### CODE REVIEW

**Comment by krcroft** [comment]
Tried hiding the cursor immediate after SDL comes to life:

``` patch

diff --git a/src/gui/sdlmain.cpp b/src/gui/sdlmain.cpp
index 2d036b89..e9355098 100644
--- a/src/gui/sdlmain.cpp
+++ b/src/gui/sdlmain.cpp
@@ -2779,6 +2779,9 @@ int main(int argc, char* argv[]) {
        // Once initialized, ensure we clean up SDL for all exit conditions
        atexit(SDL_Quit);
 
+       // Hide the mouse cursor before displaying the splash screen
+       SDL_ShowCursor(SDL_DISABLE);
+
 #ifndef DISABLE_JOYSTICK
        //Initialise Joystick separately. This way we can warn when it fails instead
        //of exiting the application
```

But it still appears on the splash screen (giving up on this and going with the update as-tested by nemo and myself).

File: src/gui/sdlmain.cpp [hunk 1]
```diff
@@ -1313,30 +1322,50 @@ static void ToggleMouseCapture(bool pressed) {
...
+ *   - current window size (full or not),
+ *   - mouse capture state, (yes or no).
+ *   - desired capture type (start, click, seamless), and
+ *   - if we're starting up for the first time,
+ *  to determine if the mouse-capture state should be toggled.
+ *  Note that this also acts a filter: we don't want to repeatedly
+ *  re-apply the same mouse capture state over and over again, so most
+ *  of the time this function will (or should) decide to do nothing.
+ */
+void GFX_UpdateMouseState(void) {
```
Comment (dreamer) [inline src/gui/sdlmain.cpp]: This is a tangent, and not exactly related to this code, so TL;DR is: let's reformat this as
```
void GFX_UpdateMouseState()
{
```
as this is C++ and not C, so we don't need to care about C89-isms ;)

### Longer explanation

Some time ago I wondered why so many programmers place `void` for function parameters, and as it turned out this is cruft of old C function declaration syntax (C89 and older). Practically nobody is using that old C syntax any more, here's an example of [how it changed](https://www.quora.com/How-have-the-function-declarations-changed-over-time-in-various-C-version-ANSI-C-C89-C95-C99-and-C11). Old syntax is not supported in C++ any more (last time it was supported was in C++85, I think) - so `int f(void);` and `int f();` mean exactly the same in C++ for more than 30 years now. In modern C old syntax it's still supported, but the C steering committee plans to drop it eventually.

I think the only reason why some programmers still use it is because they learned to program using Visual Studio in 90s (MSVC supported only C89 for looong time) and now they propagate it in cargo-cult manner.

So let's just stop preserving `void` to mean "this function takes no parameters" - it's redundant :).

Comment (krcroft) [reply src/gui/sdlmain.cpp]: I'm also surprise I didn't clean up that up :-)  This next commit mass-cleans them up in the mapper.

**Comment by dreamer** [comment]
About cursor on the splash screen: let's leave it be for now - maybe we can just change the cursor to "busy" while the splash screen is active for the time being ([SDL_CreateSystemCursor](https://wiki.libsdl.org/SDL_CreateSystemCursor)) (but as another PR, this one is just right in scope IMO).

The reason I think there's no point in spending too much time on it is: maybe we should go into the directorion of supporting copy/paste of text into DOS shell, and in such case having cursor visible during splash, and as long as "DOSBOX" DOS exec is running might be nice/necessary. The code for handling copy/paste was developed by LFN fork and can be found on our branch `vogons/lfn-r4329-2` (I'm not sure if we want to use it though).

About the change itself - a quick look at code indicates it's all good :) I want to do some additional testing. Earlier this week I noticed some weird behaviour when `seamless` and `fullscreen=true` was turned on, and I wonder if I can still reproduce it.

**Comment by dreamer** [comment]
> We still also assess the mouse state on EXPOSE events, which is fired after full - windowed modes are toggled. The EXPOSE even occurs reliably on OSX, X11, Wayland, and Windows after the window has settled (but is never fired on the Pi).

Interesting! I this info deserves to be included in comment next to code handling EXPOSE event. It's already documented in the commit message (thanks!), but this is surprising enough to be included in code comment. Please include info, that this represents SDL behaviour as of exact version you tested.

I wonder what might be the reason for it?

**Comment by krcroft** [comment]
Will drop in some comments about this. 

Yeah, the lack of the EXPOSE event might be due to the framebuffer being an exclusive surface - I don't think multiple programs can simultaneously write to the buffer and occlude eachother.

**Comment by kcgen** [comment]
Comments added; ready for review. Thx!

**Comment by dreamer** [comment]
During testing, I found a tiny bug (but I don't think it's a regression). I don't consider this a problem for this PR, so it's not a blocker.

To reproduce bug, use following settings:
```
[sdl]
fullscreen = true
capture_mouse = onstart middlerelease
```
Run some window maximised (for me it was the terminal emulator I used to start dosbox). Run dosbox, press Alt-Enter to leave fullscreen, middle-click to release the cursor. There's high chance, that click will register outside of dosbox window and WM will bring up background window instead. (problem does not happen with `seamless`, once I managed to reproduce it with `onclick`, but it's troublesome).
