### PR TITLE
Update dr_libs with fixes from upstream 

### LINKED ISSUE #138: Track upstream static analysis fixes in dr_libs
https://github.com/mackron/dr_libs/issues/112 (fixed)
https://github.com/mackron/dr_libs/issues/110 (fixed)
https://github.com/mackron/dr_libs/issues/109 (fixed)
https://github.com/mackron/dr_libs/issues/107 (fixed)
https://github.com/mackron/dr_libs/issues/103 (fixed)
https://github.com/mackron/dr_libs/issues/101 (fixed)
https://github.com/mackron/dr_libs/issues/98 (fixed)
https://github.com/mackron/dr_libs/issues/96 (fixed)

### PR DESCRIPTION
**Pull request by krcroft**
Fixes #138 
Also fixes a handful of audio-related PVS static-analysis issues.

### CODE REVIEW

File: src/dos/dos_mscdex.cpp [hunk 1]
```diff
@@ -285,7 +285,8 @@ int CMscdex::AddDrive(Bit16u _drive, char* physicalPath, Bit8u& subUnit)
 		Bit16u driverSize = sizeof(DOS_DeviceHeader::sDeviceHeader) + 10; // 10 = Bytes for 3 callbacks
 		
 		// Create Device Header
-		Bit16u seg = DOS_GetMemory(driverSize/16+((driverSize%16)>0));
+		assert((driverSize % 16) == 0); // should always be zero
```
Comment (dreamer) [inline src/dos/dos_mscdex.cpp]: Nice find :) We can make it a compile-time check this way:

```
constexpr uint16_t driverSize = sizeof(DOS_DeviceHeader::sDeviceHeader) + 10; // 10 = Bytes for 3 callbacks
// Create Device Header
static_assert((driverSize % 16) == 0); // should always be zero
```

Comment (dreamer) [reply src/dos/dos_mscdex.cpp]: Ah, sorry, C++11 requires a message in static assert:

    static_assert((driverSize % 16) == 0, "should always be zero");

**Comment by krcroft** [comment]
Very nice suggestion! Will replace these new asserts with `static_assert`.  

All credit goes to PVS Studio for figuring out these redundant or never/aways true values.  It's impressive how it does it.. and with static assert we can still retain these valiable expectations in the code (that can help future maintainers), while speeding up release builds when the asserts melt away.

**Comment by krcroft** [comment]
> I assume dr_libs had their own process for merging-in improvements

Yes; I submitted 23 issues but more than half were rejected as won't fix - not because they were false/incorrect, but because Dave preferred retaining the condition.  

A couple were actual bugs, and not just minor cleanups, which was fantastic.  

Dr_libs has an extensive regression suite he runs separate from GitHub.  I've also run tests against our use cases; as much I can exercise via DOSBox mounting and playback.

File: src/dos/dos_mscdex.cpp (hunk 1 above)
Comment (krcroft) [reply src/dos/dos_mscdex.cpp]: Darn; I can't replace either `assert` with `static_assert` because neither can be evaluated at compile-time. I suppose the PVS analyzer can dig a bit deeper than the compiler in figuring these out during static analysis. 

```
dos_mscdex.cpp: In member function ‘int CMscdex::AddDrive(Bit16u, char*, Bit8u&)’:
dos_mscdex.cpp:288:35: error: non-constant condition for static assertion
  288 |   static_assert((driverSize % 16) == 0, "should always be zero");
      |                 ~~~~~~~~~~~~~~~~~~^~~~
dos_mscdex.cpp:288:35: error: the value of ‘driverSize’ is not usable in a constant expression
dos_mscdex.cpp:285:10: note: ‘Bit16u driverSize’ is not const
```


```
dos_mscdex.cpp: In member function ‘bool CMscdex::GetDirectoryEntry(Bit16u, bool, PhysPt, PhysPt, Bit16u&)’:
dos_mscdex.cpp:714:32: error: non-constant condition for static assertion
  714 |      static_assert(entryLength <= 256, "entryLength should never exceed 256");
      |                    ~~~~~~~~~~~~^~~~~~
dos_mscdex.cpp:714:32: error: the value of ‘entryLength’ is not usable in a constant expression
```

Comment (dreamer) [reply src/dos/dos_mscdex.cpp]: Look at my first comment: `constexpr uint16_t driverSize = …` will solve that.

Comment (krcroft) [reply src/dos/dos_mscdex.cpp]: Added `assertm` as a  #define to `support.h` to make it easier to include a message, per the example here. https://en.cppreference.com/w/cpp/error/assert

Works as expected - 

```
d: dos_mscdex.cpp:289: int CMscdex::AddDrive(Bit16u, char*, Bit8u&): Assertion `((void)"should always be zero", (driverSize % 16) == 0)' failed.
```

Comment (krcroft) [reply src/dos/dos_mscdex.cpp]: The new asserts now use `assertm` (force pushed and workflow underway)

Comment (krcroft) [reply src/dos/dos_mscdex.cpp]: Sorry @dreamer ; `constexpr uint16_t` did the trick, and is indeed static.
Pushing again! Thank you for the keen eye and reminder :-)

File: include/support.h [hunk 2]
```diff
@@ -34,6 +34,11 @@
 #define strncasecmp(a, b, n) _strnicmp(a, b, n)
 #endif
 
+// Include a message in assert, similar to static_assert:
+#define assertm(exp, msg) assert(((void)msg, exp))
+// Use (void) to silent unused warnings.
+// https://en.cppreference.com/w/cpp/error/assert
+
```
Comment (dreamer) [inline include/support.h]: I didn't know about this trick, great find :)
